// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test.proto

package protobuffer

import "testing"

func TestWrite(t *testing.T) {

	Write()
}

func TestRead(t *testing.T) {
	Read()
}

func TestBenchMarkJson(t *testing.T) {
	BenchMarkJson()
}

func TestBenchMarkProto(t *testing.T) {
	BenchMarkProto()
}
